import Head from "next/head";
import React from "react";


export default function Auth() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <div>
                    <form action="/index" method="dialog">
                        <p>
                            <label htmlFor="email">Email:</label>
                            <input required type="text" id="email" name="email"/>
                        </p>

                        <p>
                            <label htmlFor="pass">Password:</label>
                            <input required type="password" id="pass" name="pass"/>
                        </p>

                        <p>
                            <button type="submit">Submit</button>
                        </p>

                    </form>
                </div>
            </main>
        </>
    );
}
