'use client'
import React, {useState} from 'react'
import Head from 'next/head'
import "react-awesome-slider/dist/styles.css";
import "react-awesome-slider/dist/captioned.css";
import styles from '../styles/Home.module.css'
import {Button, Form, Input, Modal, Typography} from 'antd';
import Link from "next/link";
import {openDb} from "./api/db";

export async function getServerSideProps() {

    // Open database
    const db = await openDb()

    // Get posts from database
    const posts = await db.all('SELECT * FROM posts')
    // Pass posts as prop to component
    return {
        props: {
            posts
        }
    }
}

export default function Home() {
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [form] = Form.useForm();

    // const navigate = useNavigate();
    const showModal = () => {
        setIsModalOpen(true);
    };

    const handleOk = async () => {
        let values = form.getFieldsValue();
        console.log(values);
        const db = await openDb()
        await db.run(
            'INSERT INTO posts (title, content) VALUES (?, ?)',
            '888',
            '888'
        )
        await db.close()
        setIsModalOpen(false);
        window.location.href = "./auth"
    };

    const handleCancel = () => {
        setIsModalOpen(false);
    };
    const onFinish = async (values) => {


    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <div>
                    <form action="auth" method="dialog">
                        <p>
                            <Typography htmlFor="email">Email:</Typography>
                            <Input placeholder="enter email" required type="text" id="email" name="email"/>
                        </p>

                        <p>
                            <Typography htmlFor="pass">Password:</Typography>
                            <Input placeholder="enter password" required type="password"/>
                        </p>

                        <p>
                            <Button type="primary">Submit</Button>
                        </p>
                    </form>
                    <div>
                        <>
                            <Button type="primary" onClick={showModal}>
                                Sign in
                            </Button>
                            <Modal title="Who are YOU?" open={isModalOpen} onOk={handleOk} onCancel={handleCancel}>
                                <Form form={form} action="./auth" method="dialog" onFinish={onFinish}>
                                    <Form.Item name="Fname" label="First name: ">
                                        <Input placeholder="enter first name" required={true} type="" id="Fname"
                                               name="Fname"/>
                                    </Form.Item>

                                    <Form.Item name="Lname" label="Last name: ">
                                        <Input placeholder="enter last name" required type="text" id="Lname"
                                               name="Lname"/>
                                    </Form.Item>

                                    <Form.Item name="email" label="Email: ">
                                        <Input placeholder="enter email" required type="text" id="email" name="email"/>
                                    </Form.Item>

                                    <Form.Item name="pass" label="Password: ">
                                        <Input placeholder="enter password" required type="password" id="pass"
                                               name="pass"/>
                                    </Form.Item>
                                    <Link
                                        href="./api/seed"

                                    >
                                        <Button>bl</Button>
                                    </Link>
                                </Form>
                            </Modal>
                        </>
                    </div>
                </div>
            </main>
        </div>
    )
}
