import React, {useState} from 'react'
import Head from 'next/head'
import "react-awesome-slider/dist/styles.css";
import "react-awesome-slider/dist/captioned.css";
import styles from '../styles/Home.module.css'
import {Button, Form, Input, Modal, Typography} from 'antd';


export default function Home() {
    const [isModalOpen, setIsModalOpen] = useState(false);
    const showModal = () => {
        setIsModalOpen(true);
    };
    const handleOk = () => {
        setIsModalOpen(false);
    };
    const handleCancel = () => {
        setIsModalOpen(false);
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>

                <div>
                    <form action="auth" method="dialog">
                        <p>
                            <Typography htmlFor="email">Email:</Typography>
                            <Input required type="text" id="email" name="email"/>
                        </p>

                        <p>
                            <Typography htmlFor="pass">Password:</Typography>
                            <Input required type="password" id="pass" name="pass"/>
                        </p>

                        <p>
                            <Button type="submit">Submit</Button>
                        </p>
                    </form>
                    <div>
                        <>
                            <Button type="primary" onClick={showModal}>
                                Open Modal
                            </Button>
                            <Modal title="Basic Modal" open={isModalOpen} onOk={handleOk} onCancel={handleCancel}>
                                <form action="auth" method="dialog">
                                    <p>
                                        <Typography htmlFor="Fname">First name:</Typography>
                                        <Input required type="text" id="Fname" name="Fname"/>
                                    </p>

                                    <p>
                                        <Typography htmlFor="Lname">Last name:</Typography>
                                        <Input required type="text" id="Lname" name="Lname"/>
                                    </p>

                                    <p>
                                        <Typography htmlFor="email">Email:</Typography>
                                        <Input required type="text" id="email" name="email"/>
                                    </p>

                                    <p>
                                        <Typography htmlFor="pass">Password:</Typography>
                                        <Input required type="password" id="pass" name="pass"/>
                                    </p>
                                </form>
                            </Modal>
                        </>
                    </div>
                </div>
            </main>
        </div>
    )
}
